FROM osrf/ros:noetic-desktop-focal

RUN apt-get update -y && apt-get install -y \
    python3-catkin-tools \
    ros-noetic-gazebo-dev \
    ros-noetic-gazebo-ros-control \
    ros-noetic-camera-info-manager \
    clang-7 \
    clang-format-7 \
    clang-tidy-7 \
    pycodestyle \
    ros-noetic-pcl-ros \
    nvidia-cuda-toolkit
